import { type Car } from "@/types/Car";

export const cars: Car[] = [
  {
    id: 1,
    filename: 'ks_audi_dtm_2020',
    brand: 'Audi',
    imgbrand: '/img/brand/audi.webp',
    model: 'RS 5 DTM 2020',
    year: 2020,
    class: 'DTM / GT500',
    power: 610,
    torque: 609,
    weight: 1056,
    description: 'Audi Sport utiliza el RS 5 Coupé en el DTM desde 2013. El coche del campeonato de la temporada 2020 vuelve a arrancar con el cuatro cilindros turbo del Audi RS 5 DTM. Es el motor más eficiente y potente en la historia de Audi en el DTM. Los ingenieros obtuvieron más de 610 CV del motor de 2 litros. Audi ha demostrado de forma impresionante la superioridad de su tecnología al ganar el título en todas las categorías.',
  },

  {
    id: 2,
    filename: 'ks_bmw_dtm_2020',
    brand: 'BMW',
    imgbrand: '/img/brand/bmw.webp',
    model: 'M4 DTM 2020',
    year: 2020,
    class: 'DTM / GT500',
    power: 610,
    torque: 609,
    weight: 1056,
    description: 'El nuevo BMW M4 DTM es el coche DTM más potente que BMW M Motorsport haya construido jamás. Equipado con potencia turbo concentrada, está listo para continuar la historia de éxito de BMW en el DTM. Más de 600 CV, un peso del vehículo significativamente reducido, velocidades máximas de hasta 300 km/h y la función Push-to-pass, introducida para la temporada 2019, hacen que la serie de turismos más disputada sea aún más rápida y espectacular.',
  },

  {
    id: 3,
    filename: 'jtc_honda_civic_eg_gra',
    brand: 'Honda',
    imgbrand: '/img/brand/honda.webp',
    model: 'Civic SiR-II (JTC Div.III)',
    year: 1991,
    class: 'JTC Div.III',
    power: 210,
    torque: 230,
    weight: 725,
    description: 'La quinta generación del Honda Civic debutó en Japón el 10 de septiembre de 1991. En su presentación en 1991, ganó el premio al Coche del Año en Japón por segunda vez. En Japón, así como en algunos otros lugares de exportación, el VTi se ofreció con dos motores diferentes: el B16A2/3 (DOHC VTEC de 160 CV) y el D15B (SOHC VTEC de 130 CV). El D15B comparte la misma cabeza que el Civic Si estadounidense (D16Z6), pero presenta un bloque, una manivela y unas bielas exclusivos. el automóvil compartía el desplazamiento de 1,5 L de los otros bloques D15, pero las varillas tenían la misma longitud que las del D16 (137 mm) y una mejor relación varilla-carrera (1,63) en lugar de la relación normal del D15 de 1,59. . A pesar de esto, los tamaños de manivela y cojinete no eran los mismos.',
  },

  {
    id: 4,
    filename: 'tatuus_ft_60',
    brand: 'Tatuus',
    imgbrand: '/img/brand/tatuus.webp',
    model: 'Toyota FT-60',
    year: 2020,
    class: 'Formula 4',
    power: 268,
    torque: 428,
    weight: 665,
    description: 'La Toyota Racing Series es una incubadora y un escaparate para la próxima generación de talentos de las carreras de Nueva Zelanda. La Serie ofrece a los conductores emergentes la oportunidad de adquirir una valiosa experiencia con chasis compuestos de fibra de carbono, aerodinámica y neumáticos lisos. Tatuus FT-60 Especificaciones técnicas Motor Toyota 8AR-FTS Motor DOHC de encendido por chispa de 4 cilindros en línea de 2,0 L (122 pulgadas cúbicas); turboalimentado, montado longitudinalmente; Motor central, disposición de tracción trasera. Transmisión SADEV SL-R 82 Caja de cambios secuencial semiautomática de 6 velocidades.',
  },

  {
    id: 5,
    filename: 'trr_acura_arx-06',
    brand: 'Acura',
    imgbrand: '/img/brand/acura.webp',
    model: 'ARX-06',
    year: 2023,
    class: 'LMDh',
    power: 584,
    torque: 505,
    weight: 1030,
    description: 'El Acura ARX-06 es un prototipo de coche de carreras deportivo diseñado por Honda Performance Development y construido por Oreca. Cuenta con carrocería y aerodinámica específicas de Acura basadas en un chasis ORECA LMDh completamente nuevo que utiliza una unidad de potencia híbrida electrificada que incluye un motor de combustión interna V6 de 2.4 litros biturbo hecho a medida, igualmente nuevo, diseñado, desarrollado y fabricado por Honda Performance Development (HPD). ). Está diseñado según las regulaciones de Le Mans Daytona h y competirá en la clase GTP en el Campeonato IMSA SportsCar1. El ARX-06 debutó junto al BMW M Hybrid V8, el Cadillac V-LMDh y el Porsche 963 en la apertura de la temporada 2023 del Campeonato IMSA SportsCar en el Daytona International Speedway.',
  },

  {
    id: 6,
    filename: 'trr_bmw_m_hybrid_V8',
    brand: 'BMW',
    imgbrand: '/img/brand/bmw.webp',
    model: 'M Hybrid v8',
    year: 2023,
    class: 'LMDh',
    power: 477,
    torque: 554,
    weight: 1080,
    description: 'El BMW M Hybrid V8 es un coche de carreras que puede considerarse la culminación de todas las tecnologías M hasta la fecha. Utiliza un chasis Dallara y está propulsado por un motor turbo de ocho cilindros P66/3 con propulsión eléctrica suplementaria. El motor de combustión se basa en la unidad DTM utilizada en el BMW M4 DTM en 2017 y 20181. El BMW M Hybrid V8 de aproximadamente 2200 libras obtiene toda su potencia eléctrica de la regeneración de los frenos. A partir de la temporada 2023, el nuevo coche luchará por la victoria absoluta en la nueva clase GTP de la serie IMSA, en clásicos tan prestigiosos como las 24 Horas de Daytona, las 12 Horas de Sebring y el icónico Petit Le Mans. en la carretera Atlanta. A partir de 2024, BMW M Motorsport también volverá a competir con este coche en el Campeonato Mundial de Resistencia de la FIA.',
  },

  {
    id: 7,
    filename: 'trr_cadillac_v-series.r',
    brand: 'Cadillac',
    imgbrand: '/img/brand/cadillac.webp',
    model: 'V-Series.R',
    year: 2023,
    class: 'LMDh',
    power: 584,
    torque: 534,
    weight: 1030,
    description: 'El Cadillac V-Series.R, originalmente llamado Cadillac V-LMDh, es un prototipo de automóvil de carreras deportivo diseñado por Cadillac y construido por Dallara. Está diseñado según las regulaciones de Le Mans Daytona h y debutó en el Campeonato IMSA SportsCar en las 24 Horas de Daytona de apertura de temporada. El coche también competirá en el Campeonato Mundial de Resistencia de la FIA a partir de 2023. La cilindrada de 5,5 litros del motor es la mayor cilindrada de cualquiera de los autos GTP que debutaron en el resurgimiento de la clase GTP en las 24 Horas de Daytona de 2023.',
  },

  {
    id: 8,
    filename: 'trr_ferrrari_499p',
    brand: 'Ferrari',
    imgbrand: '/img/brand/ferrari.webp',
    model: '499P',
    year: 2023,
    class: 'LMH',
    power: 584,
    torque: 578,
    weight: 1030,
    description: 'El Ferrari 499P es un prototipo deportivo construido por la Scuderia Ferrari para competir en el Campeonato Mundial de Resistencia de la FIA en la categoría Le Mans Hypercar. El coche fue presentado en la Ferrari Finali Mondiali, la final anual de Ferrari para su serie monomarca, Ferrari Challenge. La introducción del 499P marca 50 años desde la última vez que Ferrari presentó un prototipo deportivo respaldado por fábrica que compitió por la victoria general en las 24 Horas de Le Mans. El coche hizo su debut competitivo en la ronda inaugural de la temporada del Campeonato Mundial de Resistencia de la FIA 2023, las 1000 Millas de Sebring de 2023.',
  },

  {
    id: 9,
    filename: 'trr_peugeot_9x8',
    brand: 'Peugeot',
    imgbrand: '/img/brand/peugeot.webp',
    model: '9X8',
    year: 2022,
    class: 'LMH',
    power: 671,
    torque: 664,
    weight: 1030,
    description: 'El Peugeot 9X8 es un prototipo de carreras con tracción a las cuatro ruedas y sistema de propulsión desarrollado bajo el control de los especialistas de Peugeot Sport. El automóvil tiene un V-6 biturbo de 700 hp que impulsa las ruedas traseras y un motor eléctrico de 268 hp en el eje delantero. Las ruedas traseras están impulsadas por un motor de combustión interna (ICE) V6 biturbo de 2,6 litros y 520 kW, mientras que un motor eléctrico de alto rendimiento de 200 kW hecho a medida impulsa las ruedas delanteras. El coche pesa 2271 libras y tiene una longitud total de 196,85 pulgadas y un ancho de 78,7 pulgadas.',
  },

  {
    id: 10,
    filename: 'trr_porsche_963',
    brand: 'Porsche',
    imgbrand: '/img/brand/porsche.webp',
    model: '963',
    year: 2023,
    class: 'LMDh',
    power: 670,
    torque: 777,
    weight: 1040,
    description: 'El Porsche 963 es un prototipo de coche de carreras deportivo LMDh diseñado por Porsche y construido por Multimatic, para competir en las clases Hypercar y GTP (Grand Touring Protoype) en el Campeonato Mundial de Resistencia FIA y el Campeonato IMSA SportsCar, respectivamente. Tiene un motor V8 de 4,6 litros con doble turbocompresor, incluido el apoyo de un motor eléctrico. Con un peso de alrededor de 1.000 kilogramos, este coche de carreras tiene una potencia total de 500 kW (680 CV). El nombre 963 se inspira en los Porsche 956 y Porsche 962 que corrieron en la década de 1980 y que también compitieron en series de carreras americanas y europeas. El coche se presentó en el Festival de Velocidad de Goodwood de 2022, con una decoración tradicional roja, blanca y negra.',
  },

  {
    id: 11,
    filename: 'trr_toyota_gr010',
    brand: 'Toyota',
    imgbrand: '/img/brand/toyota.webp',
    model: 'GR010 Hybrid',
    year: 2021,
    class: 'LMH',
    power: 670,
    torque: 777,
    weight: 1030,
    description: 'El Toyota GR010 Hybrid es un prototipo de coche de carreras deportivo desarrollado para las reglas Le Mans Hypercar 2021 en el Campeonato Mundial de Resistencia de la FIA. Es el sucesor del Toyota TS050 Hybrid, que compitió en el WEC de 2016 a 2020, logrando 2 dobles títulos mundiales del WEC y 3 victorias consecutivas en las 24 Horas de Le Mans de 2018 a 2020. El GR010 HYBRID fue desarrollado por TOYOTA GAZOO Racing (TGR) para la serie 2021 del Campeonato Mundial de Resistencia (WEC) de la FIA de acuerdo con las regulaciones de Le Mans Hypercar (LMH), para competir en la clase cumbre de Hypercar.',
  },

  {
    id: 12,
    filename: 'renault_twingo_rs_twincup2',
    brand: 'Renault',
    imgbrand: '/img/brand/renault.webp',
    model: 'Twingo RS Twincup2',
    year: 2014,
    class: 'Twingo Cup',
    power: 202,
    torque: 211,
    weight: 988,
    description: 'Twingo Rs Under 8 Especificaciones: Motor:Clio 3 RS 203 cv<br/>-Transmisión:<br/>-Tipo: Tracción delantera con caja de cambios manual de 6 velocidades<br/><br/>Chasis:<br/>-Tipo: Chasis monocasco de acero 20CDF2 con jaula antivuelco. Carrocería de acero hatchback de 3 puertas con parachoques de plástico.<br/>-Suspensión Delantera: Puntal Macpherson con horquilla inferior, resorte helicoidal, amortiguador de gas telescópico y barra estabilizadora.<br/>-Suspensión Trasera: Brazo de arrastre con barra de torsión, amortiguador telescópico de gas y barra estabilizadora.<br/>-Sistema de Giro: Dirección asistida de correa y piñones<br/><br/>-Dimensiones:<br/>- Longitud: 3.607m <br/>Anchura: 1.688m <br/>Altura: 1.460m<br/>- Distancia entre ejes: 2.368 m <br/>front track: 1.460 m (54.4") <br/>rear track: 1.445 m (52.7") <br/>-Llantas - Gomas: 195/40/17Peso: 988 kg <br/>Tanque de Combustible: 45 L'
  },

  {
    id: 13,
    filename: 'alpine_europa_cup',
    brand: 'Alpine',
    imgbrand: '/img/brand/alpine.webp',
    model: 'A110 Europa Cup',
    year: 2018,
    class: 'A110 Cup',
    power: 270,
    torque: 320,
    weight: 1050,
    description: ""
  },

  {
    id: 14,
    filename: 'Le_Mans_Nascar_Camaro',
    brand: 'Chevrolet',
    imgbrand: '/img/brand/chevrolet.webp',
    model: 'Camaro Nascar Garage56',
    year: 2023,
    class: 'Nascar Le Mans',
    power: 650,
    torque: 1000,
    weight: 1450,
    description: "Hendrick Motorsports, socio de Chevrolet desde hace mucho tiempo, líder de todos los tiempos en campeonatos de la Copa NASCAR y victorias en carreras, fue seleccionado para formar el equipo y construir el auto de carreras Garage 56 Camaro ZL1. Los pilotos de renombre Jimmie Johnson, siete veces campeón de la Copa NASCAR; Jenson Button, Campeón del Mundo de Fórmula Uno 2009; y el múltiples veces ganador de Le Mans, Mike Rockenfeller, conducirá el Garage 56 Camaro ZL1 en Le Mans. Goodyear, el neumático oficial de NASCAR y el fabricante de neumáticos para todas las variantes del Camaro de sexta generación, proporciona neumáticos Goodyear Eagle para el auto de carreras Garage 56. El equipo de Ingeniería de Competición de Deportes de Motor de Chevrolet aportó más de dos décadas de conocimiento, experiencia y éxito en Le Mans con Corvette Racing para ayudar a optimizar el auto de carreras Garage 56. Los ingenieros de Chevrolet también están muy involucrados en lo que puede ser el aspecto más memorable del Garage 56 Camaro: el rugido gutural y totalmente estadounidense producido por el R07 Small Block V-8. El R07 sirve a los equipos Chevrolet en la NASCAR Cup Series, y la variante utilizada en Le Mans fue desarrollada y probada para maximizar el rendimiento y la durabilidad para la carrera de 24 horas. Convertir el Cup Camaro ZL1 en el auto de carreras Garage 56 requirió iluminación funcional específica, nuevos tratamientos aerodinámicos y una decoración destacada. El estudio de diseño de GM Motorsport ejecutó esta visión con la ayuda de Hendrick Motorsports para llevar las proporciones características del Camaro a la pista de carreras."
  },

  {
    id: 15,
    filename: '2023_Le_Mans_Nascar_Mustang',
    brand: 'Ford',
    imgbrand: '/img/brand/ford.webp',
    model: 'Mustang Nascar Garage56',
    year: 2023,
    class: 'Nascar Le Mans',
    power: 650,
    torque: 1000,
    weight: 1450,
    description: "Mustang de resistencia para Le Mans. Este Mustang tendrá muchas de las mismas cualidades de rendimiento que el Camaro y el Camry."
  },

  {
    id: 16,
    filename: '2023_Le_Mans_Nascar_Camry',
    brand: 'Toyota',
    imgbrand: '/img/brand/toyota.webp',
    model: 'Camry Nascar Garage56',
    year: 2023,
    class: 'Nascar Le Mans',
    power: 650,
    torque: 1000,
    weight: 1450,
    description: "Camry de resistencia para Le Mans. Este Camry tendrá muchas de las mismas cualidades de rendimiento que igualan tanto al Camaro original como al Mustang."
  },

  {
    id: 17,
    filename: 'trr_amr_vantage_gt3_evo',
    brand: 'Aston Martin',
    imgbrand: '/img/brand/astonmartin.webp',
    model: 'Vantage GT3 EVO',
    year: 2024,
    class: 'GT3',
    power: 447,
    torque: 603,
    weight: 1265,
    description: ""
  },

  {
    id: 18,
    filename: 'trr_ferrari_296_gt3',
    brand: 'Ferrari',
    imgbrand: '/img/brand/ferrari.webp',
    model: '296 GT3',
    year: 2023,
    class: 'GT3',
    power: 477,
    torque: 554,
    weight: 1260,
    description: "El Ferrari 296 GT3 es una versión de competición del 296 GTB, con mejoras que redefinen el rendimiento del coche en términos de preparación para la pista y exigencias estéticas. Fue presentado en el Circuito de Spa-Francorchamps antes de las 24 Horas de Spa de TotalEnergies. El 296 GT3 cuenta con un V-6 de 24 válvulas como el 296GTB de carretera, pero sin el motor eléctrico que lo acompaña, para cumplir con las regulaciones técnicas. Según Ferrari, el 296 GT3 produce un 20 por ciento más de carga aerodinámica que el 488 GT3 anterior. El motor está ubicado más adelante y más abajo, en una configuración de 120 grados con los turbos dentro de la V, para bajar el centro de gravedad y mejorar la rigidez torsional en comparación con el 488 GT3. El coche utiliza un chasis de aluminio completamente nuevo y tiene una distancia entre ejes ligeramente más larga que el coche de carretera para tener en cuenta las restricciones reglamentarias. El sistema de frenos también ha sido rediseñado para el GT3, ahora de 400 mm en el eje delantero. El Ferrari 296 GT3 representa el futuro del Cavallino Rampante en las carreras de GT, un sector que siempre ha sido testigo de la relación más estrecha con los clientes y de la mayor transferencia de tecnología y soluciones innovadoras a los coches de producción."
  },

  {
    id: 19,
    filename: 'trr_ford_mustang_gt3',
    brand: 'Ford',
    imgbrand: '/img/brand/ford.webp',
    model: 'Mustang GT3',
    year: 2024,
    class: 'GT3',
    power: 600,
    torque: 628,
    weight: 1300,
    description: "El Ford Mustang GT3 2024 es un coche de carreras desarrollado por Ford Performance para las carreras de coches deportivos a nivel mundial. Está basado en el modelo Ford Mustang Dark Horse 2024 y se ofrece a equipos de carreras privados. El coche está propulsado por un motor V8 atmosférico de 5,4 litros basado en el Coyote desarrollado por Ford Performance y M-Sport. Este motor está listo para destrozar la pista con un rendimiento emocionante y una potencia emocionante. El Mustang GT3 cuenta con una suspensión de brazo corto-largo a medida y una caja de cambios transeje montada en la parte trasera. Los paneles de la carrocería están hechos de fibra de carbono y tiene un paquete aerodinámico único. El coche está programado para comenzar a competir a nivel mundial en 2024, con participaciones en el Campeonato Mundial de Resistencia de 2024 y las 24 Horas de Le Mans. Las primeras unidades estarán disponibles para las 24 Horas de Daytona en 2024. Ford Performance continuó su asociación con Multimatic para producir este coche de carreras de precisión. Las ventas y el servicio de este vehículo estarán a cargo de Multimatic. El coche está diseñado para ayudarte a establecer récords personales en cada vuelta."
  },

  {
    id: 20,
    filename: 'trr_lexus_rcf_gt3',
    brand: 'Lexus',
    imgbrand: '/img/brand/lexus.webp',
    model: 'RC F GT3',
    year: 2016,
    class: 'GT3',
    power: 515,
    torque: 539,
    weight: 1237,
    description: "El Lexus RC F GT3 es un coche de carreras basado en el modelo de producción Lexus RC F. Cuenta con un motor V8 con más de 500 CV de potencia y una cilindrada de 5400 cc. El coche mide 4.846 mm de largo, 2.030 mm de ancho y 1.271 mm de alto, con un peso de 1.300 kg y una distancia entre ejes de 2.770 mm. La transmisión es una transeje secuencial de 6 velocidades con levas en el volante y el diseño de la tracción es 2WD. La carrocería utiliza carbono para reducir el peso y tiene formas aerodinámicas. El motor tiene un sistema de lubricación por cárter seco y está montado más abajo en el chasis que en el modelo de producción para aumentar el rendimiento en marcha. La parte trasera del coche está diseñada para producir una fuerte carga aerodinámica, con características como un alerón trasero y difusores. La cabina utiliza el mismo monocasco que el modelo de producción base e incluye una jaula antivuelco con fines de seguridad. El asiento está diseñado para una buena protección del conductor y los interruptores permiten realizar ajustes precisos en el rendimiento."
  },

  {
    id: 21,
    filename: 'trr_amg_evo_gt3',
    brand: 'Mercedes-Benz',
    imgbrand: '/img/brand/mercedes.webp',
    model: 'AMG GT3 Evo',
    year: 2020,
    class: 'GT3',
    power: 550,
    torque: 576,
    weight: 1160,
    description: "El Mercedes-AMG GT3 EVO es un extraordinario vehículo de competición que se presentó en 2020 para sustituir al anterior Mercedes-AMG GT3. Cuenta con el mismo motor que su predecesor, pero con un estilo actualizado, frenos mejorados y sistemas electrónicos. Este coche es conocido por su rendimiento y fiabilidad, gracias a su motor AMG V8 de 6,3 litros y a la lubricación por cárter seco. El motor se ha colocado especialmente bajo, lo que contribuye a una conducción precisa. Los sistemas electrónicos de control de la dinámica de conducción, desde el control de tracción hasta el ABS, se han desarrollado específicamente para fines de competición. El GT3 EVO destaca en situaciones de baja velocidad, con un potente tren delantero que mantiene el coche bajo control mientras el motor proporciona un par amplio para la aceleración. A pesar de su potencia y rendimiento, la naturaleza predecible del coche lo hace adecuado para todo tipo de conductores, desde aficionados hasta profesionales. Sin embargo, cuando se configura de forma agresiva, puede convertirse en un auténtico reto, incluso para los conductores de nivel profesional."
  },
];